version: '2'
services:
  web:
    build:
      context: .
      args:
      - APACHE_SPARK_VERSION=1.6.1
    ports:
    - "9999:9999"
    depends_on:
    - cloudera
    volumes:
    - .:/home/jovyan/work
    command: /bin/bash docker-entrypoint.sh
  cloudera:
    image: cloudera/quickstart
    command: /usr/bin/docker-quickstart
    ports:
    - "8888:8888"
    hostname: quickstart.cloudera
    privileged: true
    tty: true
